### ISSUE TITLE
Doesn't work in swift

### ISSUE THREAD

**Issue by Gargo** [mpatelCAS/MPProgressViewCell#2]
I try to import via cocoapods

Then I write `import MPProgressCell` as in your readme. Result - code is imported with dependencies but I can't use it - `No such module 'MPProgressCell'` and of course code doesn't compile

**Comment by patelmayank** [comment]
@Gargo  have u bridge the connection in your project setting,  Do this will fix your issue if not fix let me know i will fix it thanks :) 

http://stackoverflow.com/a/24005242/3800154

**Comment by Gargo** [comment]
@patelmayank I've tried both with bridging header and without it - it doesn't work

**Comment by patelmayank** [comment]
thanks let me check and update you soon :) @Gargo

**Comment by mpatelCAS** [comment]
@Gargo  Use this in your bridging header file

#import "MPProgressIndicatorCell/MPProgressCell.h"

this will fix your issue i updating this in read me file thanks.  i have shipped a new version of it,update it
